version: "3.3"
services:
  webapp:
    build:
      context: .
      dockerfile: ./src/Presentation/WebApp/Dockerfile
    ports:
      - "80:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production